// Generated by gencpp from file map_server/LoadMapRequest.msg
// DO NOT EDIT!


#ifndef MAP_SERVER_MESSAGE_LOADMAPREQUEST_H
#define MAP_SERVER_MESSAGE_LOADMAPREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace map_server
{
template <class ContainerAllocator>
struct LoadMapRequest_
{
  typedef LoadMapRequest_<ContainerAllocator> Type;

  LoadMapRequest_()
    : map_path()  {
    }
  LoadMapRequest_(const ContainerAllocator& _alloc)
    : map_path(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _map_path_type;
  _map_path_type map_path;





  typedef boost::shared_ptr< ::map_server::LoadMapRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::map_server::LoadMapRequest_<ContainerAllocator> const> ConstPtr;

}; // struct LoadMapRequest_

typedef ::map_server::LoadMapRequest_<std::allocator<void> > LoadMapRequest;

typedef boost::shared_ptr< ::map_server::LoadMapRequest > LoadMapRequestPtr;
typedef boost::shared_ptr< ::map_server::LoadMapRequest const> LoadMapRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::map_server::LoadMapRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::map_server::LoadMapRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace map_server

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::map_server::LoadMapRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::map_server::LoadMapRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::map_server::LoadMapRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::map_server::LoadMapRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::map_server::LoadMapRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::map_server::LoadMapRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::map_server::LoadMapRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "87ded74cc4428020b667445286a08b63";
  }

  static const char* value(const ::map_server::LoadMapRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x87ded74cc4428020ULL;
  static const uint64_t static_value2 = 0xb667445286a08b63ULL;
};

template<class ContainerAllocator>
struct DataType< ::map_server::LoadMapRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "map_server/LoadMapRequest";
  }

  static const char* value(const ::map_server::LoadMapRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::map_server::LoadMapRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string map_path\n\
";
  }

  static const char* value(const ::map_server::LoadMapRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::map_server::LoadMapRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.map_path);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LoadMapRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::map_server::LoadMapRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::map_server::LoadMapRequest_<ContainerAllocator>& v)
  {
    s << indent << "map_path: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.map_path);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MAP_SERVER_MESSAGE_LOADMAPREQUEST_H
