obstacle_range: 6
raytrace_range: 8
footprint: [[0.45, 0.3], [0.45, -0.3], [-0.45, -0.3], [-0.45, 0.3]]
subscribe_to_updates: true
observation_sources: laser_scan_sensor
laser_scan_sensor: {sensor_frame: laser_frame, data_type: LaserScan, topic: scan, marking: true, clearing: true}
global_frame: odom
robot_base_frame: base_footprint
always_send_full_costmap: true

