local_costmap:
  update_frequency: 5
  publish_frequency: 2
  transform_tolerance: 0.5
  static_map: false
  rolling_window: true
  width: 2
  height: 2
  origin_x: -1
  origin_y: -1
  resolution: 0.05
  inflation_radius: 0.3

