# Defines joint controllers and their PID parameters.
joint_state_ctrlr:
  type: joint_state_controller/JointStateController
  publish_rate: 30

left_front_steering_ctrlr:
  joint: left_front_steering_joint
  type: effort_controllers/JointPositionController
  pid: {p: 300.0, i: 100.0, d: 1.0}
right_front_steering_ctrlr:
  joint: right_front_steering_joint
  type: effort_controllers/JointPositionController
  pid: {p: 300.0, i: 100.0, d: 1.0}
left_rear_steering_ctrlr:
  joint: left_rear_steering_joint
  type: effort_controllers/JointPositionController
  pid: {p: 300.0, i: 100.0, d: 1.0}
right_rear_steering_ctrlr:
  joint: right_rear_steering_joint
  type: effort_controllers/JointPositionController
  pid: {p: 300.0, i: 100.0, d: 1.0}

left_front_axle_ctrlr:
  joint: left_front_axle
  type: effort_controllers/JointVelocityController
  pid: {p: 1, i: 10, d: 0, i_clamp: 300.0}
right_front_axle_ctrlr:
  joint: right_front_axle
  type: effort_controllers/JointVelocityController
  pid: {p: 1, i: 10, d: 0, i_clamp: 300.0}
left_rear_axle_ctrlr:
  joint: left_rear_axle
  type: effort_controllers/JointVelocityController
  pid: {p: 1, i: 10, d: 0, i_clamp: 300.0}
right_rear_axle_ctrlr:
  joint: right_rear_axle
  type: effort_controllers/JointVelocityController
  pid: {p: 1, i: 10, d: 0, i_clamp: 300.0}

